version: 1.0.{build}

install:
  - cinst java.jdk
  - cinst groovy
  - cinst scala.install
  - cinst maven
  - cinst apache.ant
  - cinst sbt
  - cinst gradle
  
before_build:
  - gradle :wrapper
  
before_build:
  - gradle :wrapper
  
build_script:
  - gradlew :build
  
test_script:
  - gradlew :test